import Navbar from "@/components/Navbar";
import config from "@/config/env_config";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    fcs: any;
    fluidChatSettings: any;
    fluidSettings: any;
    Spreedly: any;
    showCartCount: Function;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="fluid-widget-boot" strategy="beforeInteractive">
          {`
          window.fcs = {api_url_host: '${config.apiHost}'};
          (function(){ var f_ws = document.createElement('script'); f_ws.async = true; f_ws.src = '${config.widgetHost}'; x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(f_ws,x); })();
        `}
        </Script>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${inter.className} h-screen`}>
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
